// Pure-CSR entry used ONLY for the Electron (file://) build.
// The normal web preview uses TanStack Start SSR — this bundle is standalone.
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter, createMemoryHistory } from "@tanstack/react-router";
import { QueryClient } from "@tanstack/react-query";

import "./fonts.css";
import "../src/styles.css";
// Loaded last so it wins over the shared web styles.
import "./desktop.css";
// Desktop-only route tree — generated by vite.electron.config.mjs without the
// server routes (api/**, admin.licenses) that require a Start SSR runtime.
import { routeTree } from "../src/routeTree.electron.gen";

// Route the app's `confirm(...)` / `alert(...)` calls through real Windows
// message boxes. Chromium's own dialogs are unmistakably a web page's — wrong
// font, English buttons, and a title bar that names the document.
const native = (
  window as unknown as {
    erpNative?: {
      confirmSync?: (message: string) => boolean;
      alertSync?: (message: string) => boolean;
    };
  }
).erpNative;

if (native?.confirmSync) {
  window.confirm = (message?: string) => native.confirmSync!(message ?? "");
}
if (native?.alertSync) {
  window.alert = (message?: string) => void native.alertSync!(message ?? "");
}

const queryClient = new QueryClient();

const router = createRouter({
  routeTree,
  context: { queryClient },
  history: createMemoryHistory({ initialEntries: ["/"] }),
  defaultPreload: "intent",
  defaultPreloadStaleTime: 0,
  scrollRestoration: true,
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const el = document.getElementById("root")!;
createRoot(el).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
);
