// Pure-CSR entry used ONLY for the Electron (file://) build.
// The normal web preview uses TanStack Start SSR — this bundle is standalone.
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter, createMemoryHistory } from "@tanstack/react-router";
import { QueryClient } from "@tanstack/react-query";

import "./fonts.css";
import "../src/styles.css";
// Desktop-only route tree — generated by vite.electron.config.mjs without the
// server routes (api/**, admin.licenses) that require a Start SSR runtime.
import { routeTree } from "../src/routeTree.electron.gen";

const queryClient = new QueryClient();

const router = createRouter({
  routeTree,
  context: { queryClient },
  history: createMemoryHistory({ initialEntries: ["/"] }),
  defaultPreload: "intent",
  defaultPreloadStaleTime: 0,
  scrollRestoration: true,
});

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

const el = document.getElementById("root")!;
createRoot(el).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
);
