/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as PriceTiersRouteImport } from './routes/price-tiers'
import { Route as PurchaseOrderRouteImport } from './routes/purchase-order'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AdminLicensesRouteImport } from './routes/admin.licenses'
import { Route as ApiPublicLicenseActivateRouteImport } from './routes/api/public/license/activate'
import { Route as ApiPublicLicenseBackupRouteImport } from './routes/api/public/license/backup'
import { Route as ApiPublicLicenseBundleRouteImport } from './routes/api/public/license/bundle'
import { Route as ApiPublicLicenseDeactivateRouteImport } from './routes/api/public/license/deactivate'
import { Route as ApiPublicLicenseHeartbeatRouteImport } from './routes/api/public/license/heartbeat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceTiersRoute = PriceTiersRouteImport.update({
  id: '/price-tiers',
  path: '/price-tiers',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrderRoute = PurchaseOrderRouteImport.update({
  id: '/purchase-order',
  path: '/purchase-order',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLicensesRoute = AdminLicensesRouteImport.update({
  id: '/admin/licenses',
  path: '/admin/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseActivateRoute =
  ApiPublicLicenseActivateRouteImport.update({
    id: '/api/public/license/activate',
    path: '/api/public/license/activate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseBackupRoute = ApiPublicLicenseBackupRouteImport.update({
  id: '/api/public/license/backup',
  path: '/api/public/license/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseBundleRoute = ApiPublicLicenseBundleRouteImport.update({
  id: '/api/public/license/bundle',
  path: '/api/public/license/bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseDeactivateRoute =
  ApiPublicLicenseDeactivateRouteImport.update({
    id: '/api/public/license/deactivate',
    path: '/api/public/license/deactivate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseHeartbeatRoute =
  ApiPublicLicenseHeartbeatRouteImport.update({
    id: '/api/public/license/heartbeat',
    path: '/api/public/license/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/expenses': typeof ExpensesRoute
  '/home': typeof HomeRoute
  '/items': typeof ItemsRoute
  '/price-tiers': typeof PriceTiersRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/backup': typeof ApiPublicLicenseBackupRoute
  '/api/public/license/bundle': typeof ApiPublicLicenseBundleRoute
  '/api/public/license/deactivate': typeof ApiPublicLicenseDeactivateRoute
  '/api/public/license/heartbeat': typeof ApiPublicLicenseHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/expenses': typeof ExpensesRoute
  '/home': typeof HomeRoute
  '/items': typeof ItemsRoute
  '/price-tiers': typeof PriceTiersRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/backup': typeof ApiPublicLicenseBackupRoute
  '/api/public/license/bundle': typeof ApiPublicLicenseBundleRoute
  '/api/public/license/deactivate': typeof ApiPublicLicenseDeactivateRoute
  '/api/public/license/heartbeat': typeof ApiPublicLicenseHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/expenses': typeof ExpensesRoute
  '/home': typeof HomeRoute
  '/items': typeof ItemsRoute
  '/price-tiers': typeof PriceTiersRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/rates': typeof RatesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/admin/licenses': typeof AdminLicensesRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/backup': typeof ApiPublicLicenseBackupRoute
  '/api/public/license/bundle': typeof ApiPublicLicenseBundleRoute
  '/api/public/license/deactivate': typeof ApiPublicLicenseDeactivateRoute
  '/api/public/license/heartbeat': typeof ApiPublicLicenseHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/expenses'
    | '/home'
    | '/items'
    | '/price-tiers'
    | '/purchase-order'
    | '/rates'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/admin/licenses'
    | '/api/public/license/activate'
    | '/api/public/license/backup'
    | '/api/public/license/bundle'
    | '/api/public/license/deactivate'
    | '/api/public/license/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/expenses'
    | '/home'
    | '/items'
    | '/price-tiers'
    | '/purchase-order'
    | '/rates'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/admin/licenses'
    | '/api/public/license/activate'
    | '/api/public/license/backup'
    | '/api/public/license/bundle'
    | '/api/public/license/deactivate'
    | '/api/public/license/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/expenses'
    | '/home'
    | '/items'
    | '/price-tiers'
    | '/purchase-order'
    | '/rates'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/admin/licenses'
    | '/api/public/license/activate'
    | '/api/public/license/backup'
    | '/api/public/license/bundle'
    | '/api/public/license/deactivate'
    | '/api/public/license/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  ExpensesRoute: typeof ExpensesRoute
  HomeRoute: typeof HomeRoute
  ItemsRoute: typeof ItemsRoute
  PriceTiersRoute: typeof PriceTiersRoute
  PurchaseOrderRoute: typeof PurchaseOrderRoute
  RatesRoute: typeof RatesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  UsersRoute: typeof UsersRoute
  AdminLicensesRoute: typeof AdminLicensesRoute
  ApiPublicLicenseActivateRoute: typeof ApiPublicLicenseActivateRoute
  ApiPublicLicenseBackupRoute: typeof ApiPublicLicenseBackupRoute
  ApiPublicLicenseBundleRoute: typeof ApiPublicLicenseBundleRoute
  ApiPublicLicenseDeactivateRoute: typeof ApiPublicLicenseDeactivateRoute
  ApiPublicLicenseHeartbeatRoute: typeof ApiPublicLicenseHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-tiers': {
      id: '/price-tiers'
      path: '/price-tiers'
      fullPath: '/price-tiers'
      preLoaderRoute: typeof PriceTiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-order': {
      id: '/purchase-order'
      path: '/purchase-order'
      fullPath: '/purchase-order'
      preLoaderRoute: typeof PurchaseOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/licenses': {
      id: '/admin/licenses'
      path: '/admin/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AdminLicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/activate': {
      id: '/api/public/license/activate'
      path: '/api/public/license/activate'
      fullPath: '/api/public/license/activate'
      preLoaderRoute: typeof ApiPublicLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/backup': {
      id: '/api/public/license/backup'
      path: '/api/public/license/backup'
      fullPath: '/api/public/license/backup'
      preLoaderRoute: typeof ApiPublicLicenseBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/bundle': {
      id: '/api/public/license/bundle'
      path: '/api/public/license/bundle'
      fullPath: '/api/public/license/bundle'
      preLoaderRoute: typeof ApiPublicLicenseBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/deactivate': {
      id: '/api/public/license/deactivate'
      path: '/api/public/license/deactivate'
      fullPath: '/api/public/license/deactivate'
      preLoaderRoute: typeof ApiPublicLicenseDeactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/heartbeat': {
      id: '/api/public/license/heartbeat'
      path: '/api/public/license/heartbeat'
      fullPath: '/api/public/license/heartbeat'
      preLoaderRoute: typeof ApiPublicLicenseHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  ExpensesRoute: ExpensesRoute,
  HomeRoute: HomeRoute,
  ItemsRoute: ItemsRoute,
  PriceTiersRoute: PriceTiersRoute,
  PurchaseOrderRoute: PurchaseOrderRoute,
  RatesRoute: RatesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  UsersRoute: UsersRoute,
  AdminLicensesRoute: AdminLicensesRoute,
  ApiPublicLicenseActivateRoute: ApiPublicLicenseActivateRoute,
  ApiPublicLicenseBackupRoute: ApiPublicLicenseBackupRoute,
  ApiPublicLicenseBundleRoute: ApiPublicLicenseBundleRoute,
  ApiPublicLicenseDeactivateRoute: ApiPublicLicenseDeactivateRoute,
  ApiPublicLicenseHeartbeatRoute: ApiPublicLicenseHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
