/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchaseOrderRouteImport } from './routes/purchase-order'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ExchangeRatesRouteImport } from './routes/exchange-rates'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicLicenseHeartbeatRouteImport } from './routes/api/public/license/heartbeat'
import { Route as ApiPublicLicenseActivateRouteImport } from './routes/api/public/license/activate'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrderRoute = PurchaseOrderRouteImport.update({
  id: '/purchase-order',
  path: '/purchase-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRatesRoute = ExchangeRatesRouteImport.update({
  id: '/exchange-rates',
  path: '/exchange-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLicenseHeartbeatRoute =
  ApiPublicLicenseHeartbeatRouteImport.update({
    id: '/api/public/license/heartbeat',
    path: '/api/public/license/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseActivateRoute =
  ApiPublicLicenseActivateRouteImport.update({
    id: '/api/public/license/activate',
    path: '/api/public/license/activate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/exchange-rates': typeof ExchangeRatesRoute
  '/expenses': typeof ExpensesRoute
  '/home': typeof HomeRoute
  '/items': typeof ItemsRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/heartbeat': typeof ApiPublicLicenseHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/exchange-rates': typeof ExchangeRatesRoute
  '/expenses': typeof ExpensesRoute
  '/home': typeof HomeRoute
  '/items': typeof ItemsRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/heartbeat': typeof ApiPublicLicenseHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/exchange-rates': typeof ExchangeRatesRoute
  '/expenses': typeof ExpensesRoute
  '/home': typeof HomeRoute
  '/items': typeof ItemsRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/users': typeof UsersRoute
  '/api/public/license/activate': typeof ApiPublicLicenseActivateRoute
  '/api/public/license/heartbeat': typeof ApiPublicLicenseHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/exchange-rates'
    | '/expenses'
    | '/home'
    | '/items'
    | '/purchase-order'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/api/public/license/activate'
    | '/api/public/license/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/exchange-rates'
    | '/expenses'
    | '/home'
    | '/items'
    | '/purchase-order'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/api/public/license/activate'
    | '/api/public/license/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/exchange-rates'
    | '/expenses'
    | '/home'
    | '/items'
    | '/purchase-order'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/api/public/license/activate'
    | '/api/public/license/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  ExchangeRatesRoute: typeof ExchangeRatesRoute
  ExpensesRoute: typeof ExpensesRoute
  HomeRoute: typeof HomeRoute
  ItemsRoute: typeof ItemsRoute
  PurchaseOrderRoute: typeof PurchaseOrderRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  UsersRoute: typeof UsersRoute
  ApiPublicLicenseActivateRoute: typeof ApiPublicLicenseActivateRoute
  ApiPublicLicenseHeartbeatRoute: typeof ApiPublicLicenseHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-order': {
      id: '/purchase-order'
      path: '/purchase-order'
      fullPath: '/purchase-order'
      preLoaderRoute: typeof PurchaseOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange-rates': {
      id: '/exchange-rates'
      path: '/exchange-rates'
      fullPath: '/exchange-rates'
      preLoaderRoute: typeof ExchangeRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/heartbeat': {
      id: '/api/public/license/heartbeat'
      path: '/api/public/license/heartbeat'
      fullPath: '/api/public/license/heartbeat'
      preLoaderRoute: typeof ApiPublicLicenseHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/activate': {
      id: '/api/public/license/activate'
      path: '/api/public/license/activate'
      fullPath: '/api/public/license/activate'
      preLoaderRoute: typeof ApiPublicLicenseActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  ExchangeRatesRoute: ExchangeRatesRoute,
  ExpensesRoute: ExpensesRoute,
  HomeRoute: HomeRoute,
  ItemsRoute: ItemsRoute,
  PurchaseOrderRoute: PurchaseOrderRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  UsersRoute: UsersRoute,
  ApiPublicLicenseActivateRoute: ApiPublicLicenseActivateRoute,
  ApiPublicLicenseHeartbeatRoute: ApiPublicLicenseHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
